theme: jekyll-theme-cayman
title: Agroganadera ROEDGA
description: Calidad Bovina Y Equina
domain: ralarco2.github.io      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://ralarco2.github.io # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /ralarco2.github.io/   # place folder name if the site is served in a subfolder
